### ISSUE TITLE
gud-lldb: junk characters

### ISSUE THREAD

**Issue by yasushi-saito** [junjiemars/.emacs.d#56]
Thanks for gud-lldb, but I had to change defcustom% to defcustom and ignore* to ignore to make it work.

**Comment by junjiemars** [comment]
It's not junk characters, `defcustom%` and `ignore*` are those compile-time macro and help to generate better run-time code, you can translate `defcustom%` and `ignore*` back to builtin ones. 

for `defcustom%`: just remove `%` character.
for `ignore*`: just remove the `ignore*` sexp.

And if you want to know what those macro does, you can find it here:
[defcustom%](https://github.com/junjiemars/.emacs.d/blob/b6801677b4c4787d345e73ad54b9472689f42cf0/config/basic.el)
[ignore*](https://github.com/junjiemars/.emacs.d/blob/b6801677b4c4787d345e73ad54b9472689f42cf0/config/strap.el)

**Comment by yasushi-saito** [comment]
Ah, ok. I missed that since I was looking at only the gud-lldb.el.
